In [1]:
class FileInformation(object):
    fileName = ''
    mp4FileName = ''
    jpgFileName = ''
    jpgFileList = []
    slowFileName = ''

In [35]:
from keras.models import load_model
import h5py
# returns a compiled model
# identical to the previous one
model = load_model('/home/ubuntu/Insight/mymodel.h5')

In [2]:
import Config
import os
from fileInfo import FileInformation

def getImageList(directory, fileName):
    dirList = os.listdir(directory)
    imageList = []
    rImageName = ''

    for item in dirList:
        if item is not None and (item.lower().find('png') or item.lower().find('jpg')) and item.find(fileName) > -1:
            imageList.append(item)
            if item.lower().endswith('.jpg'):
                rImageName = item

    return imageList, rImageName

def getmp4List(directory):
    dirList = os.listdir(directory)
    rList = []
    imageList = []
    slowList = []
    #f = fileInfo


    for item in dirList:
        if item is not None and item.find('.mp4') > -1:
            if not item in rList:
                f = FileInformation()
                f.jpgFileList,\
                    f.jpgFileName = getImageList(directory + 'FRAMES/', item.replace('.mp4', ''))
                f.fileName = item.replace('.mp4', '')
                f.mp4FileName = item
                if len(imageList) > 0:
                    f.jpgFileName = imageList[0]
                rList.append(f)

    return rList

In [11]:
videoName = 'balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA'
imageList = []
category = ''
Npredictions = []
Vprediction = []
    

In [60]:
for item in nonviolentList:
    if item.fileName == videoName:
        print(item.fileName)
        print(item.jpgFileList)
        imageList = item.jpgFileList
        category = 'nonviolent'
        impath = 'static/images/violent/' 
        

balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA
['balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA3.jpg', 'balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA1.jpg', 'balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA2.jpg']


In [61]:
vidpath = os.path.join(impath,'FRAMES')

In [62]:
vidpath

'static/images/violent/FRAMES'

In [63]:
for i in imageList:
    print(i)

balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA3.jpg
balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA1.jpg
balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA2.jpg


In [54]:
from PIL import Image
import os, os.path

In [19]:
from keras.models import load_model
import h5py
from keras.preprocessing import image
from keras.applications.imagenet_utils import decode_predictions

def preprocess_input(x):
    x /= 255.
    x -= 0.5
    x *= 2.
    return x

Using TensorFlow backend.


In [72]:
for i in imageList:
    current_img = image.load_img(os.path.join(vidpath,i), target_size=(299,299))
    x = image.img_to_array(current_img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    Npredictions.append(model.predict(x))

In [73]:
Npredictions

[array([[ 0.90577197,  0.094228  ]], dtype=float32),
 array([[ 0.82444966,  0.17555034]], dtype=float32),
 array([[ 0.90577197,  0.09422796]], dtype=float32),
 array([[ 0.94859159,  0.0514084 ]], dtype=float32)]

In [64]:
current_img = image.load_img(os.path.join(vidpath,imageList[1]), target_size=(299, 299))

In [71]:
for i in imageList:
    print(i)

balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA3.jpg
balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA1.jpg
balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA2.jpg


In [70]:
c, imageList

('balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA2.jpg',
 ['balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA3.jpg',
  'balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA1.jpg',
  'balcony_football_violence__British_Football_Hooligans_Mix_1__MorningGlory1997__pn6CNLi3UhA2.jpg'])

In [36]:
x = image.img_to_array(current_img)
import numpy as np
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)
Npredictions.append(model.predict(x))

In [37]:
Npredictions

[array([[ 0.90577197,  0.094228  ]], dtype=float32)]